apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjdXJlcGFzcw==  # base64 encoded 'securepass'
  MYSQL_USER: bXl1c2Vy  # base64 encoded 'myuser'
  MYSQL_PASSWORD: c2VjdXJlcGFzcw==  # base64 encoded 'securepass'
