apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: default
type: Opaque
data:
  DB_USER: bXl1c2Vy  # base64 encoded 'myuser'
  DB_PASSWORD: c2VjdXJlcGFzcw==  # base64 encoded 'securepass'
